/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javabankproject;

/**
 *
 * @author Novin Pendar
 */
public class JDialogAdminMenu extends javax.swing.JDialog {

    /**
     * Creates new form JDialogAdminMenu
     * @param parent
     * @param modal
     */
    public JDialogAdminMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonAddCity = new javax.swing.JRadioButton();
        jRadioButtonAddBranch = new javax.swing.JRadioButton();
        jRadioButtonAddUser = new javax.swing.JRadioButton();
        jRadioButtonDisplayCity = new javax.swing.JRadioButton();
        jRadioButtonDisplayBranch = new javax.swing.JRadioButton();
        jRadioButtonReturn = new javax.swing.JRadioButton();
        jButtonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Menu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Choose one of the follwoing.");

        buttonGroup1.add(jRadioButtonAddCity);
        jRadioButtonAddCity.setText("Add new city");

        buttonGroup1.add(jRadioButtonAddBranch);
        jRadioButtonAddBranch.setText("Add new branch");

        buttonGroup1.add(jRadioButtonAddUser);
        jRadioButtonAddUser.setText("Add new user");

        buttonGroup1.add(jRadioButtonDisplayCity);
        jRadioButtonDisplayCity.setText("Display exist city list");
        jRadioButtonDisplayCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDisplayCityActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonDisplayBranch);
        jRadioButtonDisplayBranch.setText("Display exist branch list");

        buttonGroup1.add(jRadioButtonReturn);
        jRadioButtonReturn.setText("Return to main menu");

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAddCity)
                            .addComponent(jRadioButtonAddBranch)
                            .addComponent(jRadioButtonAddUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonReturn)
                            .addComponent(jRadioButtonDisplayBranch)
                            .addComponent(jRadioButtonDisplayCity))))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jButtonOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAddCity)
                    .addComponent(jRadioButtonDisplayCity))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAddBranch)
                    .addComponent(jRadioButtonDisplayBranch))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAddUser)
                    .addComponent(jRadioButtonReturn))
                .addGap(18, 18, 18)
                .addComponent(jButtonOk)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonDisplayCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDisplayCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDisplayCityActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed

        if (jRadioButtonAddCity.isSelected()) {
            JDialogAddCity jdialogAddCity = new JDialogAddCity(null, true);
            jdialogAddCity.setVisible(true);
        } else if (jRadioButtonDisplayCity.isSelected()) {
            JDialogDisplayCity jdialogDisplayCity = new JDialogDisplayCity(null, true);
            jdialogDisplayCity.setVisible(true);
        } else if (jRadioButtonAddBranch.isSelected()) {
            JDialogAddBranch jDialogAddBranch = new JDialogAddBranch(null, true);
            jDialogAddBranch.setVisible(true);
        } else if (jRadioButtonDisplayBranch.isSelected()) {
            JDialogDisplayBranch jDialogDisplayBranch = new JDialogDisplayBranch(null, true);
            jDialogDisplayBranch.setVisible(true);
        } else if (jRadioButtonAddUser.isSelected()) {
            JDialogAddUser jDialogAddUser = new JDialogAddUser(null, true);
            jDialogAddUser.setVisible(true);
        } else if (jRadioButtonReturn.isSelected()) {
            this.dispose();
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogAdminMenu dialog = new JDialogAdminMenu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonAddBranch;
    private javax.swing.JRadioButton jRadioButtonAddCity;
    private javax.swing.JRadioButton jRadioButtonAddUser;
    private javax.swing.JRadioButton jRadioButtonDisplayBranch;
    private javax.swing.JRadioButton jRadioButtonDisplayCity;
    private javax.swing.JRadioButton jRadioButtonReturn;
    // End of variables declaration//GEN-END:variables
}
