/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javabankproject;

import java.util.ArrayList;
import javabankproject.Data.User;
import javabankproject.Data.Manager.CityManager;
import javabankproject.Data.Branch;
import javabankproject.Data.City;
import javabankproject.Data.Roles;
import javabankproject.Data.Manager.UserManager;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Novin Pendar
 */
public class JDialogAddUser extends javax.swing.JDialog {

    /**
     * Creates new form JDialogAddUser
     */
    public JDialogAddUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        drawComboBoxCity();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelNationalCode = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelLAstName = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelPosition = new javax.swing.JLabel();
        jTextFieldNationalCode = new javax.swing.JTextField();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jRadioButtonAdmin = new javax.swing.JRadioButton();
        jRadioButtonStaff = new javax.swing.JRadioButton();
        jRadioButtonClient = new javax.swing.JRadioButton();
        jButtonSave = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jComboBoxCity = new javax.swing.JComboBox();
        jLabelCity = new javax.swing.JLabel();
        jLabelBranch = new javax.swing.JLabel();
        jComboBoxBranch = new javax.swing.JComboBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add User");

        jLabelNationalCode.setText("National code");

        jLabelFirstName.setText("First name");

        jLabelLAstName.setText("Last name");

        jLabelPassword.setText("Password");

        jLabelPosition.setText("Position");

        jTextFieldNationalCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNationalCodeActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonAdmin);
        jRadioButtonAdmin.setText("Admin");
        jRadioButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAdminActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonStaff);
        jRadioButtonStaff.setText("Staff");
        jRadioButtonStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStaffActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonClient);
        jRadioButtonClient.setText("Client");
        jRadioButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAdminActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jComboBoxCity.setEnabled(false);
        jComboBoxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCityActionPerformed(evt);
            }
        });

        jLabelCity.setText("City");
        jLabelCity.setEnabled(false);

        jLabelBranch.setText("Branch");
        jLabelBranch.setEnabled(false);

        jComboBoxBranch.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jButtonSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelNationalCode, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(jLabelFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelLAstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonAdmin)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonStaff)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonClient))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldNationalCode, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                            .addComponent(jTextFieldFirstName)
                                            .addComponent(jTextFieldLastName)
                                            .addComponent(jPasswordField)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCity, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxBranch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNationalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNationalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLAstName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonAdmin)
                    .addComponent(jRadioButtonStaff)
                    .addComponent(jRadioButtonClient))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCity, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButtonSave)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNationalCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNationalCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNationalCodeActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
        long nationalCode = Long.parseLong(jTextFieldNationalCode.getText()) ;
        String firstName = jTextFieldFirstName.getText() ;
        String lastName = jTextFieldLastName.getText() ;
        char [] password = jPasswordField.getPassword() ;
        
        if (jRadioButtonStaff.isSelected())
        {
            String branchName = (String)jComboBoxBranch.getSelectedItem() ;
            String cityName = (String)jComboBoxCity.getSelectedItem() ;
            
            Branch branch = CityManager.manager.findBranch(branchName, cityName) ;
            
            User usr = new User(nationalCode, password, firstName, lastName, Roles.staff, branch) ;
            boolean exist = UserManager.manager.addUser(usr);
            
            if (!exist)
            {
                JOptionPane.showMessageDialog(this, new String("This person is already one of your staffs."));
            }
        }
        
        else if (jRadioButtonAdmin.isSelected())
        {
            User usr = new User(nationalCode, password, firstName, lastName, Roles.Admin) ;
            boolean exist = UserManager.manager.addUser(usr);
            
            if (!exist)
            {
                JOptionPane.showMessageDialog(this, new String("This information is equal to yours."));
            }
        }
        
        else if (jRadioButtonClient.isSelected())
        {
            User usr = new User(nationalCode, password, firstName, lastName, Roles.client) ;
            boolean exist = UserManager.manager.addUser(usr);
            
            if (!exist)
            {
                JOptionPane.showMessageDialog(this, new String("This person is already one of your clients."));
            }
        }
        
        else
        {
            JOptionPane.showMessageDialog(this, new String("Please fill all the fallowing."));
            
            this.dispose();
            
            JDialogAddUser jdialogAddUser = new JDialogAddUser(null, true) ;
            jdialogAddUser.setVisible(true);
        }
//        ArrayList<String> array = new ArrayList<String>() ;
//        array.add(lastName);
       
        this.dispose();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * If the radio button for staff selected, the city and branch would be enable. 
     * @param evt 
     */
    private void jRadioButtonStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonStaffActionPerformed
       
        jComboBoxCity.setEnabled(true);
        jLabelCity.setEnabled(true);
        jComboBoxBranch.setEnabled(true);
        jLabelBranch.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonStaffActionPerformed

    private void jRadioButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAdminActionPerformed
        
        jComboBoxCity.setEnabled(false);
        jLabelCity.setEnabled(false);
        jComboBoxBranch.setEnabled(false);
        jLabelBranch.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonAdminActionPerformed

    private void jComboBoxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCityActionPerformed
        
        String cityName = (String)jComboBoxCity.getSelectedItem() ;
        
        drawComboBoxBranch(cityName) ;
    }//GEN-LAST:event_jComboBoxCityActionPerformed

    private void drawComboBoxBranch (String cityName)
    {
        DefaultComboBoxModel Model=(DefaultComboBoxModel) this.jComboBoxBranch.getModel();
        
        Model.removeAllElements();
        
        for (Branch branch : CityManager.manager.getBranch())
        {
            if (branch != null)
            {
                if (cityName.equals(branch.getCity().getName())) 
                {
                    Model.addElement(branch.getName());
                }
            }
        }
    }
    
    private void drawComboBoxCity ()
    {
        DefaultComboBoxModel Model=(DefaultComboBoxModel) this.jComboBoxCity.getModel();
        
        for (City city : CityManager.manager.getCity())
        {
            if(city != null)
            {
                Model.addElement(city.getName());
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogAddUser dialog = new JDialogAddUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxBranch;
    private javax.swing.JComboBox jComboBoxCity;
    private javax.swing.JLabel jLabelBranch;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelLAstName;
    private javax.swing.JLabel jLabelNationalCode;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JRadioButton jRadioButtonAdmin;
    private javax.swing.JRadioButton jRadioButtonClient;
    private javax.swing.JRadioButton jRadioButtonStaff;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldNationalCode;
    // End of variables declaration//GEN-END:variables
}
