/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javabankproject;

import javabankproject.Data.User;
import javabankproject.Data.Manager.UserManager;
import javabankproject.Data.Branch;
import javabankproject.Data.Account;
import javabankproject.Data.AccountType;
import javax.swing.JOptionPane;
import javabankproject.Data.Roles;

/**
 *
 * @author Novin Pendar
 */
public class JDialogCreateAccount extends javax.swing.JDialog {

    /**
     * Creates new form JDialogCreateAccount
     */
    public JDialogCreateAccount(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSave = new javax.swing.JButton();
        jLabelNationalCode = new javax.swing.JLabel();
        jTextFieldNationalCode = new javax.swing.JTextField();
        jRadioButtonShortTerm = new javax.swing.JRadioButton();
        jRadioButtonInterestFreeLoan = new javax.swing.JRadioButton();
        jLabelAccountType = new javax.swing.JLabel();
        jRadioButtonCurrent = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabelNationalCode.setText("National code");

        jRadioButtonShortTerm.setText("Short-term account");
        jRadioButtonShortTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonShortTermActionPerformed(evt);
            }
        });

        jRadioButtonInterestFreeLoan.setText("Interest Free Loan account");

        jLabelAccountType.setText("Account type");

        jRadioButtonCurrent.setText("Current account");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAccountType)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNationalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jTextFieldNationalCode))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jRadioButtonShortTerm)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSave)
                                    .addComponent(jRadioButtonInterestFreeLoan))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonCurrent)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabelAccountType)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonShortTerm)
                    .addComponent(jRadioButtonInterestFreeLoan)
                    .addComponent(jRadioButtonCurrent))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNationalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNationalCode))
                .addGap(29, 29, 29)
                .addComponent(jButtonSave)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonShortTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonShortTermActionPerformed
        
         
    }//GEN-LAST:event_jRadioButtonShortTermActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
        long nationalCode = Long.parseLong(jTextFieldNationalCode.getText()) ;
        User owner = UserManager.manager.findUser(nationalCode) ;
        
        if (owner.getRole() == Roles.client)
        {
            if (jRadioButtonShortTerm.isSelected())
            {
                int id = UserManager.manager.addAccount(AccountType.ShortTerm, UserManager.manager.userTemp.getBranch(), owner);
                JOptionPane.showMessageDialog(this, new String("Your account number is " + id + "."));
            }

            if (jRadioButtonInterestFreeLoan.isSelected())
            {
                int id = UserManager.manager.addAccount(AccountType.InterestFreeLoan, UserManager.manager.userTemp.getBranch(), owner);
                JOptionPane.showMessageDialog(this, new String("Your account number is " + id + "."));
            }

            if (jRadioButtonCurrent.isSelected())
            {
                int id = UserManager.manager.addAccount(AccountType.Current, UserManager.manager.userTemp.getBranch(), owner);
                JOptionPane.showMessageDialog(this, new String("Your account number is " + id + "."));
            }
        }
        
        else
            JOptionPane.showMessageDialog(this, new String("You are not one of our clients."));
        
        this.dispose();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCreateAccount dialog = new JDialogCreateAccount(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelAccountType;
    private javax.swing.JLabel jLabelNationalCode;
    private javax.swing.JRadioButton jRadioButtonCurrent;
    private javax.swing.JRadioButton jRadioButtonInterestFreeLoan;
    private javax.swing.JRadioButton jRadioButtonShortTerm;
    private javax.swing.JTextField jTextFieldNationalCode;
    // End of variables declaration//GEN-END:variables
}
