/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javabankproject;

/**
 *
 * @author Novin Pendar
 */
public class JDialogStaffMenu extends javax.swing.JDialog {

    /**
     * Creates new form JDialogStaffMenu
     */
    public JDialogStaffMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonCreateAccount = new javax.swing.JRadioButton();
        jRadioButtonWithdraw = new javax.swing.JRadioButton();
        jRadioButtonDeposit = new javax.swing.JRadioButton();
        jRadioButtonTransfer = new javax.swing.JRadioButton();
        jRadioButtonDisplayInfo = new javax.swing.JRadioButton();
        jRadioButtonIssuingCard = new javax.swing.JRadioButton();
        jRadioButtonReturn = new javax.swing.JRadioButton();
        jRadioButtonAddUser = new javax.swing.JRadioButton();
        jButtonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Staff Menu");

        buttonGroup1.add(jRadioButtonCreateAccount);
        jRadioButtonCreateAccount.setText("Create new account");

        buttonGroup1.add(jRadioButtonWithdraw);
        jRadioButtonWithdraw.setText("Withdraw money");

        buttonGroup1.add(jRadioButtonDeposit);
        jRadioButtonDeposit.setText("Deposit");

        buttonGroup1.add(jRadioButtonTransfer);
        jRadioButtonTransfer.setText("Transfer money");

        buttonGroup1.add(jRadioButtonDisplayInfo);
        jRadioButtonDisplayInfo.setText("Display account information");

        buttonGroup1.add(jRadioButtonIssuingCard);
        jRadioButtonIssuingCard.setText("Issuing new card");

        buttonGroup1.add(jRadioButtonReturn);
        jRadioButtonReturn.setText("Return to main menu");

        buttonGroup1.add(jRadioButtonAddUser);
        jRadioButtonAddUser.setText("Add new user");

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonWithdraw)
                            .addComponent(jRadioButtonAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonDisplayInfo)
                            .addComponent(jRadioButtonTransfer))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonReturn)
                            .addComponent(jRadioButtonCreateAccount)
                            .addComponent(jRadioButtonDeposit)
                            .addComponent(jRadioButtonIssuingCard)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButtonOk)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAddUser)
                    .addComponent(jRadioButtonCreateAccount))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonWithdraw)
                    .addComponent(jRadioButtonDeposit))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDisplayInfo)
                    .addComponent(jRadioButtonIssuingCard))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonReturn)
                    .addComponent(jRadioButtonTransfer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        
        if (jRadioButtonAddUser.isSelected())
        {
            JDialogAddUserByStaff jDialogAddUserByStaff = new JDialogAddUserByStaff(null, true) ;
            jDialogAddUserByStaff.setVisible(true);
        }
        
        if (jRadioButtonCreateAccount.isSelected())
        {
            JDialogCreateAccount jDialogCreateAccount = new JDialogCreateAccount(null, true) ;
            jDialogCreateAccount.setVisible(true);
        }
        
        if (jRadioButtonWithdraw.isSelected())
        {
            JDialogWithdraw jDialogWithdraw = new JDialogWithdraw(null, true) ;
            jDialogWithdraw.setVisible(true);
        }
        
        if (jRadioButtonDeposit.isSelected())
        {
            JDialogDeposit jDialogDeposit = new JDialogDeposit(null, true) ;
            jDialogDeposit.setVisible(true);
        }
        
        if (jRadioButtonDisplayInfo.isSelected())
        {
            JDialogDisplayInfo jDialogDisplayInfo = new JDialogDisplayInfo(null, true) ;
            jDialogDisplayInfo.setVisible(true);
        }
        
        if (jRadioButtonIssuingCard.isSelected())
        {
            IssueCard jDialogIssueCard = new IssueCard(null, true) ;
            jDialogIssueCard.setVisible(true);
        }
        
        if (jRadioButtonTransfer.isSelected())
        {
            JDialogTransferMoney jDialogTransferMoney = new JDialogTransferMoney(null, true) ;
            jDialogTransferMoney.setVisible(true);
        }
        
        if (jRadioButtonReturn.isSelected())
        {
            this.dispose();
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogStaffMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogStaffMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogStaffMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogStaffMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogStaffMenu dialog = new JDialogStaffMenu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JRadioButton jRadioButtonAddUser;
    private javax.swing.JRadioButton jRadioButtonCreateAccount;
    private javax.swing.JRadioButton jRadioButtonDeposit;
    private javax.swing.JRadioButton jRadioButtonDisplayInfo;
    private javax.swing.JRadioButton jRadioButtonIssuingCard;
    private javax.swing.JRadioButton jRadioButtonReturn;
    private javax.swing.JRadioButton jRadioButtonTransfer;
    private javax.swing.JRadioButton jRadioButtonWithdraw;
    // End of variables declaration//GEN-END:variables
}
